# Generated by Django 3.2.16 on 2022-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_reg',
            field=models.BooleanField(default=False),
        ),
    ]
